FROM public.ecr.aws/lambda/python:3.12

# Install pipenv
RUN pip install pipenv

# Copy dependency files
COPY Pipfile* ${LAMBDA_TASK_ROOT}/

# Install dependencies
WORKDIR ${LAMBDA_TASK_ROOT}
RUN pipenv install --skip-lock --system --deploy --ignore-pipfile

# Copy application code
COPY ./api ${LAMBDA_TASK_ROOT}/api
COPY ./data ${LAMBDA_TASK_ROOT}/data

# Set the CMD to your handler
CMD ["api.main.handler"]
