name: deploy
description: Deploy Copilot service
inputs:
  folder: 
    description: 'The folder to run deploy from'
    required: true
  environment: 
    description: 'The environment to deploy to'
    required: true
  aws-access-key-id:
    required: true
    type: string
  aws-secret-access-key:
    required: true
    type: string
  aws-region:
    required: true
    type: string



runs:
  using: "composite"
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}
    - name: Install AWS CDK
      shell: bash
      run: npm install -g aws-cdk
      - uses: "actions/setup-python@v4"
      with:
        python-version: "3.12"
    - name: Deploy CDK Stack
      shell: bash
      run: |
        cd ${{inputs.folder}}/deployment
        pip install -r requirements.txt
        cdk context --clear
        cdk --context deployment_context=${{inputs.environment}} deploy --require-approval never
