name: Deploy Authentication Dev

on:
  workflow_run:
    workflows: ["Python tests authentication"]
    branches: [main]
    types:
      - completed
  workflow_dispatch:
    branches:
      - kip/*

env:
  AWS_REGION: eu-west-2 # set this to your preferred AWS region, e.g. us-west-1

jobs:
  deploy-authentication-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Deploy authentication docs
        uses: ./.github/templates/deploy_docs/
        with:
          folder: authentication
          deployment_context: authentication-prod
