name: Deploy Resource Dev

on:
  workflow_run:
    workflows: ["Python tests resource"]
    branches: [preprod]
    types:
      - completed
  workflow_dispatch:
    branches:
      - kip/*

env:
  AWS_REGION: eu-west-2 # set this to your preferred AWS region, e.g. us-west-1

jobs:
  deploy-resource-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Deploy resource
        uses: ./.github/templates/deploy/
        with:
          folder: resource
          environment: dev
          service_name: perseus-resource
