name: Test and deploy authentication and resource services

on: [push]

env:
  ENVIRONMENT: ${{ github.ref == 'refs/heads/main' && 'prod' || github.ref == 'refs/heads/preprod' && 'dev' || 'feature'}}
jobs:
  test-authentication:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Run tests
        uses: ./.github/templates/test/
        with:
          folder: authentication
  test-resource:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Run tests
        uses: ./.github/templates/test/
        with:
          folder: resource
  deploy-authentication:
    runs-on: ubuntu-latest
    needs: test-authentication
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/preprod'
    steps:
      - uses: actions/checkout@v4
      - name: Deploy authentication
        uses: ./.github/templates/deploy/
        with:
          folder: authentication
          environment: ${{ env.ENVIRONMENT }}
          service_name: backend
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Deploy Redis
        uses: ./.github/templates/deploy/
        with:
          folder: authentication
          environment: ${{ env.ENVIRONMENT }}
          service_name: redis
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
  deploy-authentication-docs:
    runs-on: ubuntu-latest
    needs: test-authentication
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/preprod'
    steps:
      - uses: actions/checkout@v4
      - name: Deploy authentication docs
        uses: ./.github/templates/deploy_docs/
        with:
          folder: authentication
          deployment_context: authentication-${{ env.ENVIRONMENT }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
  deploy-resource:
    runs-on: ubuntu-latest
    needs: test-resource
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/preprod'
    steps:
      - uses: actions/checkout@v4
      - name: Deploy resource
        uses: ./.github/templates/deploy/
        with:
          folder: resource
          environment: ${{ env.ENVIRONMENT }}
          service_name: perseus-resource
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
  deploy-resource-docs:
    runs-on: ubuntu-latest
    needs: test-resource
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/preprod'
    steps:
      - uses: actions/checkout@v4
      - name: Deploy resource docs
        uses: ./.github/templates/deploy_docs/
        with:
          folder: resource
          deployment_context: resource-${{ env.ENVIRONMENT }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
